### PR TITLE
Updates to meet handbook requirements

### PR DESCRIPTION
**Pull request by jonahgraham**
Here is the work to bring up the website to the requirements. 

I'm waiting for https://eclipse-embed-cdt.github.io/web-preview/ to be up to date. 

Please review and let me know.

PS. The one thing I didn't do is add the from year to the copyright footer. It currently auto generates the to year (2020) but https://www.eclipse.org/projects/handbook/#ip-copyright-headers says that generally the copyright line should say:

> The {year} is the year in which the content was created (e.g. “2004”). The date may optionally be set to a range of years with the first and last years of the range separated by a comma (e.g. “2004, 2017”); in this case, the first year is when the content was first created and the last year is when the content was last modified.

But I didn't know what the initial year was.

### CODE REVIEW

**Comment by ilg-ul** [comment]
> I didn't know what the initial year was

I would use 2009.

if the new copyright line gets too long after adding the initial year, split it.

> Please review and let me know.

I'm not particularly fond of the position of the large logo taking a lot of space in the footer.

Do you know how to rearrange things on three columns?

I suggest to place the logo in the middle, between the two columns with text, such that it takes less vertical space.

What do you think?

**Comment by jonahgraham** [comment]
> > I didn't know what the initial year was
> 
> I would use 2009.
> 
> if the new copyright line gets too long after adding the initial year, split it.

OK. I added 2009 and split it.

> 
> > Please review and let me know.
> 
> I'm not particularly fond of the position of the large logo taking a lot of space in the footer.
> 
> Do you know how to rearrange things on three columns?
> 
> I suggest to place the logo in the middle, between the two columns with text, such that it takes less vertical space.
> 
> What do you think?

Yes to all and done.

Here is what it looks like (while waiting for travis):

image

**Comment by ilg-ul** [comment]
I think it looks decent.

Shouldn't the the two years in the copyright notice be separated by a dash, to mean range?

**Comment by jonahgraham** [comment]
> I think it looks decent.

Great. 


> 
> Shouldn't the the two years in the copyright notice be separated by a dash, to mean range? 

No, see example from handbook quoted above.

**Review by ilg-ul — APPROVED** [review]
Fine with me.

**Comment by ilg-ul** [comment]
How do you suggest to proceed, to ask the review guys to check this preview site to possibly add more improvements, and merge it when approved?

**Comment by jonahgraham** [comment]
No. Just merge it now and let them know it is done.

**Comment by ilg-ul** [comment]
Thank you!

I hope that the workflow did not make you any problems. It is a bit more elaborate than usual, with a separate preview site, but I find Jekyll + a CI job to automatically generate the content quite convenient to use. Not to mention that all pages can be edited directly via the GitHub web interface, from anywhere.

**Comment by jonahgraham** [comment]
The workflow was OK. Sadly the versions of bundler that came with my package manager on Ubuntu were too old so I had to jump through some hoops to install bundler locally, but once that was done and I figured out how to get watch to work then it was fairly fast iterating to test out my changes.

**Comment by ilg-ul** [comment]
> I had to jump through some hoops to install bundler locally

Can you document these steps, in case others will face the same problem? 

I have a separate folder with a Homebrew instance, where Ruby and bundler are installed, and when I need it, I add it to the PATH; I never thought that an older bundler can be a problem.

**Pull request merged**
